COMPONENT=SigFoxTMPDemoAppC

# Required to print information over console
CFLAGS += -DPRINTFUART_ENABLED

# Enable to override demo mode and enter test mode: send AT\n to TD120x
# CFLAGS += -DAT_TEST_MODE

include $(MAKERULES)
